import type { Metadata } from "next";
import Header from "@/components/shared/header/Header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import PageButton from "@/components/ui/PageButton";
import Footer from "@/components/shared/Footer";
import '../../styles/globals.css'
import ProviderLayout from "@/components/ui/ProviderLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-display">
        <ProviderLayout>
        <Header />
        <PageButton/>
        {children}
        <Footer/>
        </ProviderLayout>
      </body>
    </html>
  );
}
